name: "Run Aries Test Harness"
description: "Run the Aries Test Harness test suite with the specified Agents"
author: "iancostanzo@gmail.com"
inputs:
  DEFAULT_AGENT:
    description: "Default agent image for all roles"
    required: false
    default: "acapy"
  BOB_AGENT:
    description: "Specific agent image for the bob role"
    required: false
    default: "acapy"
runs:
  using: "composite"
  steps:
    - name: build-test-harness
      run: ./manage build -a ${{ inputs.DEFAULT_AGENT }} -a ${{ inputs.BOB_AGENT }}
      shell: bash
      working-directory: test-harness
    - name: run-test-harness-acapy
      run: ./manage run -d ${{ inputs.DEFAULT_AGENT }} -b ${{ inputs.BOB_AGENT }} -t @AcceptanceTest -t ~@wip
      shell: bash
      env:
        NO_TTY: "1"
      working-directory: test-harness
branding:
  icon: "mic"
  color: "purple"
