version: "3"
services:
  ngrok-tails-server:
    image: ngrok/ngrok
    networks:
      - tails-server
    ports:
      - 4044:4040
    command: http tails-server:6543 --log stdout
  tails-server:
    image: ghcr.io/bcgov/tails-server:1.0.0
    ports:
      - 6543:6543
    networks:
      - tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO
networks:
  tails-server:
