name: generate-aath-summary-results
on:
  workflow_dispatch:
  schedule:
    - cron: "45 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: generate-summary-results
        uses: ./test-harness/actions/run-summary-results
