name: test-harness-acapy-acapy
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: build-test-harness
        run: ./manage build -a acapy
        working-directory: test-harness
      - name: run-test-harness-acapy
        run: ./manage run -d acapy -t @AcceptanceTest -t ~@wip
        env:
          NO_TTY: "1"
        working-directory: test-harness
